apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: working
  url: https://github.com/achirazi/NexaSphere