apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-appp
  namespace: default
spec:
  interval: 15m
  path: "./app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-app
