apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: default
spec:
  interval: 15m
  path: "./app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo-app
