repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--args=--disable-rule=terraform_unused_declarations'
      - id: terraform_docs
      - id: terraform_checkov
        args:
          - '--args=--quiet --enable-secret-scan-all-files --compact'