apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/achirazi/NexaSphere
  branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nexasphere
  namespace: flux
spec:
  interval: 10m0s
  path: ./cluster/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux
  validation: client
