name: Infrastructure Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Check Terraform
      run: terraform init
      working-directory: infra

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: infra
      env:
        TF_VAR_my_public_key: ${{ secrets.PUBLIC_KEY }}
        TF_VAR_github_token: ${{ secrets.TOKEN }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: infra
      env:
        TF_VAR_my_public_key: ${{ secrets.PUBLIC_KEY }}
        TF_VAR_github_token: ${{ secrets.TOKEN }}
