name: Infrastructure Deploy
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Terraform Validate
      run: terraform validate
      working-directory: infra

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: infra

